[package]
name = "filecooker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive", "cargo"] }
colored = "3.0.0"
dialoguer = "0.11.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"